
// 30 min
const iat = Math.floor(Date.now() / 1000)
const exp = iat + 60

const TOKEN_DETAILS = {
  JWT_SECRET_KEY: "BACKENDPROJECTBYNIAMUDEEN",
  REFRESH_SECRET_KEY: "BACKENDPROJECTBYNIAMUDEEN",
  ACCESS_TOKEN_EXPIRATION_TIME: exp,
  REFRESH_TOKEN_EXPIRATION_TIME: "1h",
  // ACCESS_TOKEN_COOKIE_EXPIRATION_TIME: 30 * 1000,
  // REFRESH_TOKEN_COOKIE_EXPIRATION_TIME: 30 * 24 * 60 * 60 * 1000,
};

module.exports = TOKEN_DETAILS;
